version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - finance_agent
      - operations_agent
      - commercial_agent
    networks:
      - mecsol-net

  frontend:
    build: ./frontend
    container_name: frontend_ui
    networks:
      - mecsol-net

  finance_agent:
    build: ./backend/finance_agent
    container_name: finance_agent_service
    networks:
      - mecsol-net

  operations_agent:
    build: ./backend/operations_agent
    container_name: operations_agent_service
    networks:
      - mecsol-net

  commercial_agent:
    build: ./backend/commercial_agent
    container_name: commercial_agent_service
    networks:
      - mecsol-net

networks:
  mecsol-net:
    driver: bridge
